### ISSUE TITLE
Identify the location to set custom environment variables in a workflow

### ISSUE THREAD

**Issue by lfarci** [lfarci/github-actions#15]

**Comment by lfarci** [comment]
In a GitHub Actions workflow, you can set custom environment variables at three levels:

Workflow level: You can set environment variables that apply to all jobs in the workflow. This is done under the env key at the root level of the workflow.

Job level: You can set environment variables that apply to all steps in a job. This is done under the env key within a job.

Step level: You can set environment variables that apply only to a specific step. This is done under the env key within a step.

```yaml
name: Conditional env variable

on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
```

[Variables](https://docs.github.com/en/actions/learn-github-actions/variables#about-variables)
[Set custom environment variables](https://youtu.be/NJR0HZABHRI?si=IGR1KwRi1q-wRg7g)
