### ISSUE TITLE
Use CodeQL as a step in a workflow

### ISSUE THREAD

**Issue by lfarci** [lfarci/github-actions#23]

**Comment by lfarci** [comment]
[Exam Pro](https://youtu.be/pnEfSQheScA?si=9WTwSl0FsqSxYFjS)

Here's a short example:
```yaml
name: "CodeQL"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: "auto"

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
```
