### ISSUE TITLE
Deploy a release to a cloud provider using a GitHub Actions workflow

### ISSUE THREAD

**Issue by lfarci** [lfarci/github-actions#25]

**Comment by lfarci** [comment]
```yaml
name: Deploy to Azure Web App

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './'

```
