### ISSUE TITLE
Identify the metadata and syntax needed to create an action

### ISSUE THREAD

**Issue by lfarci** [lfarci/github-actions#52]

**Comment by lfarci** [comment]
```yaml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
```

[Creating an action metadata file](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#creating-an-action-metadata-file)
